### ISSUE TITLE
Some tables are not necessary when use tomlkit.dumps()

### ISSUE THREAD

**Issue by wchengru** [sdispater/tomlkit#107]
Hi there,

I am using tomlkit.dumps() to generate toml file from a nested dict. Below please find an example:

```
>>> import tomlkit
>>> toml_dict = {'version':0.1, 'layer1':{'layer2':{'layer3':{'myKey':'myValue'}}}}
>>> mystr = tomlkit.dumps(toml_dict)
>>> print(mystr)
version = 0.1

[layer1]
[layer1.layer2]
[layer1.layer2.layer3]
myKey = "myValue"
``` 
Here tables `[layer1]` and `[layer1.layer2]` are not necessary for us because removing these two tables work as well. I was wondering if we can remove them and generate only the necessary tables.

**Comment by bosatsu** [comment]
I believe I am also seeing this issue.  When trying to add a section to the toml file by amending the dictionary directly(without using a new `table()`),  unneeded headings are added and spacing is off:

```
{'tool': {'poetry': {'name': 'cleanup_aurora_replicas', 'version': '1.0.3', 'packages': [{'include': 'cleanup_aurora_replicas', 'from': 'src'}], 'dependencies': {'python': '~3.7', 'boto3': '==1.9.77', 'requests': '==2.22.0'}, 'dev-dependencies': {'pytest': '^5.4.2', 'pytest-env': '^0.6.2', 'pytest-cov': '^2.8.1', 'flake8': '^3.7.9'}}, 'pytest': {'ini_options': {'env': ['HOME=~/tmp', 'RUN_ENV=test']}}}, 'build-system': {'requires': ['poetry>=0.12'], 'build-backend': 'poetry.masonry.api'}}
```

```
[tool.poetry]
name = "cleanup_aurora_replicas"
version = "1.0.3"
packages = [
    { include = "cleanup_aurora_replicas", from = "src"}
]

[tool.poetry.dependencies]
python = "~3.7"
boto3 = "==1.9.77"
requests = "==2.22.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-env = "^0.6.2"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"


[tool.pytest]
[tool.pytest.ini_options]
env = ["HOME=~/tmp", "RUN_ENV=test"]
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

However using `table()` and setting the heading as `tool.pytest.ini_options` so that part of the dictionary looks like `tool.pytest.ini_options': {'env': ['HOME=~/tmp', 'RUN_ENV=test']}` seems to work.e

**Comment by bosatsu** [comment]
Found the issue here is that if you want a toml section that is nested, for example `tool.pytest.ini_options` then everything but the last table must be a `super_table`, as defined [here](https://github.com/sdispater/tomlkit/blob/master/tomlkit/items.py#L879).  Unfortunately there doesn't seem to be an API method to create a `super_table`, so for the time being I just created a `table()` and then updated the private method `_is_super_table` to `True`.  Would be nice if `table()` excepted a parameter to set super_table to true or an API method to create a super_table.  Could probably create a PR for that if it would be helpful.

In case anyone else needs to do something similar, here is a quick script that demonstrates how to add an additional section to an existing toml file:

```
import tomlkit

test_pyproject_toml = """
[tool.poetry]
name = "test"
version = "0.0.0"
packages = [
    { include = "test_package", from = "src"}
]

[tool.poetry.dependencies]
python = "~3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
"""


def main():
    new_section = "foo.bar.baz"
    section_list = new_section.split('.')
    key = 'test_key'
    value = 'test_value'
    toml_dict = tomlkit.parse(test_pyproject_toml)
    print("#" * 12 + "\nBEFORE\n" + "#" * 12)
    print(tomlkit.dumps(toml_dict))
    toml_dict.add(tomlkit.nl())
    temp_dict = toml_dict
    for section_item in section_list[:-1]:
        if not temp_dict.get(section_item):
            new_table = tomlkit.table()
            new_table._is_super_table = True
            temp_dict[section_item] = new_table
        temp_dict = temp_dict[section_item]
    final_table = tomlkit.table()
    final_table.add(key, value)
    final_table.add(tomlkit.nl())
    final_section = section_list[-1]
    temp_dict[final_section] = final_table
    print("\n\n" + "#" * 12 + "\nAFTER\n" + "#" * 12)
    print(tomlkit.dumps(toml_dict))


if __name__ == "__main__":
    main()
```

**Comment by frostming** [comment]
Duplicate with #47
