### ISSUE TITLE
setup.py installs the tests package

### ISSUE THREAD

**Issue by dgilman** [sdispater/tomlkit#69]
This might be partly a bug in poetry but the sdist tarball's setup.py installs the tests package alongside the tomlkit package.

**Comment by jtrakk** [comment]
`tomlkit`'s `tests` directory caused a [collision in nixpkgs](https://github.com/NixOS/nixpkgs/issues/81482). As I said in my Poetry PR, 

If multiple distributions have `tests` as a top-level package, they'll conflict whenever both are installed. (Examples [here](https://github.com/python-poetry/poetry/issues/1905) and [here](https://github.com/NixOS/nixpkgs/issues/81482)). Two common alternative strategies are:

1. not distributing tests (as [here](https://github.com/pypa/sampleproject)), or 
2. placing tests in a subdirectory of the main package, rather than adjacent (as [here](http://blog.habnab.it/blog/2013/07/21/python-packages-and-you/) and [here](http://as.ynchrono.us/2007/12/filesystem-structure-of-python-project_21.html)). 

Either of these strategies will avoid this issue.

**Comment by wgjak47** [comment]
This problem also happen in gentoo.
```
 * ERROR: dev-python/tomlkit-0.7.0::gentoo-zh failed (install phase):
 *   Package installs 'tests' package which is forbidden and likely a bug in the build system.
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_install
 *   environment, line 2962:  Called distutils-r1_src_install
 *   environment, line 1187:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_install'
 *   environment, line  439:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 2576:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 2058:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 2056:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line  778:  Called distutils-r1_run_phase 'distutils-r1_python_install'
 *   environment, line 1155:  Called distutils-r1_python_install
 *   environment, line 1074:  Called die
 * The specific snippet of code:
 *               die "Package installs '${p}' package which is forbidden and likely a bug in the build system.";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/tomlkit-0.7.0::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/tomlkit-0.7.0::gentoo-zh'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/tomlkit-0.7.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/tomlkit-0.7.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/tomlkit-0.7.0/work/tomlkit-0.7.0'
 * S: '/var/tmp/portage/dev-python/tomlkit-0.7.0/work/tomlkit-0.7.0'
```

**Comment by bollwyvl** [comment]
Also conda-forge: https://github.com/conda-forge/tomlkit-feedstock/issues/24

We'd love the tests to be _present_ in the sdist (a la `recursive-include tests *` and `include_package_data=True`) so we can run them, but excluded (a la `find_packages(".", exclude=["tests*"])` so they don't cause this conflict. Alas, I do not know the `poetry` constructs for these techniques.

**Comment by bollwyvl** [comment]
Perhaps:
```toml
[tool.poetry]
# ...
include = ["tests"]
```
and omit the line about including the tests in the `sdist`. I presume the `whl` will then have them, too, but that's another issue for another day, i suppose...

**Comment by kwshi** [comment]
Relevant issue from Poetry: https://github.com/python-poetry/poetry/issues/2353
